# Generated by Django 5.0.6 on 2024-06-05 09:46

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.upload_to)),
                ('name', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
